/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ljh' at '16-11-10 上午5:30' with Gradle 2.14.1
 *
 * @author ljh, @date 16-11-10 上午5:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
